name: Build Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive  # 自动拉取 libzt 子模块

    - name: Install dependencies
      run: |
        apt update
        apt install -y clang cmake make git

    - name: Build
      run: |
        make  # 运行 Makefile，编译 libzt 并生成 pylon

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pylon-linux
        path: pylon  # 上传生成的 pylon 可执行文件
